from __future__ import annotations

import asyncio
import os
from datetime import UTC, datetime, timedelta

import pytest
from sqlalchemy import text

from pe_review_agent.config import DatabaseSettings
from pe_review_agent.db import Database
from pe_review_agent.domain import (
    Finding,
    FindingLocation,
    GerritPatchsetEvent,
    JobState,
    ReviewResult,
    Severity,
)
from pe_review_agent.jobs import JobStore

DSN = os.environ.get("PE_REVIEW_TEST_POSTGRES_DSN")
pytestmark = pytest.mark.skipif(not DSN, reason="PE_REVIEW_TEST_POSTGRES_DSN is not configured")


def _event(*, patchset: int, revision: str) -> GerritPatchsetEvent:
    return GerritPatchsetEvent(
        project="team/fw",
        change_number=101,
        patchset_number=patchset,
        revision_sha=revision,
        ref=f"refs/changes/01/101/{patchset}",
        branch="main",
    )


def _review() -> ReviewResult:
    return ReviewResult(
        summary="One actionable firmware defect was found.",
        model="Qwen3.6-27B",
        input_tokens=100,
        output_tokens=20,
        findings=[
            Finding(
                severity=Severity.P1,
                category="timeout",
                title="Timeout is treated as success",
                message="The timeout path still advances the state machine.",
                impact="The next stage can consume stale training data.",
                evidence="poll_done() returns -ETIMEDOUT but the caller discards it.",
                remediation="Propagate or explicitly handle the timeout.",
                location=FindingLocation(path="fw/train.c", start_line=42),
                confidence=0.97,
            )
        ],
    )


@pytest.fixture
async def store():
    assert DSN is not None
    database = Database(DatabaseSettings(dsn=DSN, pool_size=4, max_overflow=2))
    async with database.session() as session:
        await session.execute(
            text(
                "TRUNCATE review_publications, review_findings, review_results, "
                "review_attempts, review_jobs RESTART IDENTITY CASCADE"
            )
        )
        await session.commit()
    try:
        yield JobStore(database.sessions), database
    finally:
        await database.close()


@pytest.mark.asyncio
async def test_durable_review_and_publication_resume_after_crash(store) -> None:
    jobs, database = store
    event = _event(patchset=1, revision="a" * 40)

    first, created = await jobs.enqueue(event, review_policy_version="firmware-v1")
    duplicate, duplicate_created = await jobs.enqueue(event, review_policy_version="firmware-v1")
    assert created is True
    assert duplicate_created is False
    assert duplicate.id == first.id

    claimed = await jobs.claim_next(worker_id="worker-a", lease_seconds=120)
    assert claimed is not None and claimed.id == first.id
    claimed = await jobs.transition(first.id, JobState.FETCHING, worker_id="worker-a")
    claimed = await jobs.transition(first.id, JobState.REVIEWING, worker_id="worker-a")
    claimed = await jobs.transition(first.id, JobState.VALIDATING, worker_id="worker-a")
    ready = await jobs.save_review_result_and_mark_ready(first.id, _review(), worker_id="worker-a")
    assert ready.state == JobState.READY_TO_PUBLISH
    assert ready.lease_owner is None

    recovered_review = await jobs.load_review_result(first.id)
    assert recovered_review is not None
    assert recovered_review.summary == _review().summary
    assert len(recovered_review.findings) == 1
    assert recovered_review.findings[0].fingerprint

    publish_claim = await jobs.claim_next(worker_id="worker-b", lease_seconds=120)
    assert publish_claim is not None and publish_claim.state == JobState.READY_TO_PUBLISH
    await jobs.transition(first.id, JobState.PUBLISHING, worker_id="worker-b")
    payload = {
        "message": recovered_review.summary,
        "tag": "autogenerated:pe-ai-review",
        "omit_duplicate_comments": True,
    }
    publication = await jobs.begin_publication(
        first.id,
        worker_id="worker-b",
        request_payload=payload,
        finding_fingerprints=[recovered_review.findings[0].fingerprint or ""],
    )

    # Simulate a hard process crash after durable publication intent but before a Gerrit response
    # could be recorded: the lease simply expires while state remains PUBLISHING/PENDING.
    async with database.session() as session:
        await session.execute(
            text(
                "UPDATE review_jobs SET lease_expires_at = :expired "
                "WHERE id = CAST(:job_id AS uuid)"
            ),
            {
                "expired": datetime.now(UTC) - timedelta(seconds=1),
                "job_id": str(first.id),
            },
        )
        await session.commit()

    reclaimed = await jobs.claim_next(worker_id="worker-c", lease_seconds=120)
    assert reclaimed is not None
    assert reclaimed.id == first.id
    assert reclaimed.state == JobState.PUBLISHING
    publication_again = await jobs.begin_publication(
        first.id,
        worker_id="worker-c",
        request_payload=payload,
        finding_fingerprints=[recovered_review.findings[0].fingerprint or ""],
    )
    assert publication_again.id == publication.id

    await jobs.complete_publication(publication.id, gerrit_response={"ok": True})
    done = await jobs.mark_done(first.id, worker_id="worker-c")
    assert done.state == JobState.DONE


@pytest.mark.asyncio
async def test_new_patchset_supersedes_older_durable_job(store) -> None:
    jobs, _database = store
    old, _ = await jobs.enqueue(
        _event(patchset=1, revision="a" * 40), review_policy_version="firmware-v1"
    )
    new, _ = await jobs.enqueue(
        _event(patchset=2, revision="b" * 40), review_policy_version="firmware-v1"
    )

    old_after = await jobs.get(old.id)
    new_after = await jobs.get(new.id)
    assert old_after is not None and old_after.state == JobState.SUPERSEDED
    assert new_after is not None and new_after.state == JobState.RECEIVED


@pytest.mark.asyncio
async def test_concurrent_claims_do_not_take_same_job(store) -> None:
    jobs, _database = store
    one, _ = await jobs.enqueue(
        _event(patchset=1, revision="a" * 40), review_policy_version="firmware-v1"
    )
    two_event = _event(patchset=1, revision="b" * 40).model_copy(
        update={"change_number": 102, "ref": "refs/changes/02/102/1"}
    )
    two, _ = await jobs.enqueue(two_event, review_policy_version="firmware-v1")

    first_claim, second_claim = await asyncio.gather(
        jobs.claim_next(worker_id="worker-a", lease_seconds=120),
        jobs.claim_next(worker_id="worker-b", lease_seconds=120),
    )
    assert first_claim is not None and second_claim is not None
    assert {first_claim.id, second_claim.id} == {one.id, two.id}
