from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, Field, SecretStr


class GerritRestAuth(BaseModel):
    mode: Literal["none", "basic", "bearer"] = "none"
    username: str | None = None
    password_env: str | None = None
    token_env: str | None = None

    def secret(self) -> str | None:
        env_name = self.password_env if self.mode == "basic" else self.token_env
        return os.environ.get(env_name) if env_name else None


class GerritSettings(BaseModel):
    ssh_host: str
    ssh_port: int = Field(default=29418, ge=1, le=65535)
    ssh_user: str
    ssh_key_path: Path
    known_hosts_path: Path | None = None
    strict_host_key_checking: bool = True
    rest_url: str
    rest_auth: GerritRestAuth = Field(default_factory=GerritRestAuth)
    projects: list[str] = Field(min_length=1)
    event_reconnect_min_seconds: float = Field(default=1.0, gt=0)
    event_reconnect_max_seconds: float = Field(default=60.0, gt=0)
    request_timeout_seconds: float = Field(default=20.0, gt=0)
    review_tag: str = "autogenerated:pe-ai-review"
    notify: Literal["NONE", "OWNER", "OWNER_REVIEWERS", "ALL"] = "OWNER"


class LlmSettings(BaseModel):
    base_url: str
    model: str = "Qwen3.6-27B"
    api_key_env: str = "PE_REVIEW_LLM_API_KEY"
    request_timeout_seconds: float = Field(default=180.0, gt=0)
    connect_timeout_seconds: float = Field(default=10.0, gt=0)
    max_retries: int = Field(default=4, ge=0, le=20)
    concurrency: int = Field(default=2, ge=1, le=64)
    temperature: float = Field(default=0.1, ge=0.0, le=2.0)
    max_output_tokens: int = Field(default=6000, ge=256)

    @property
    def api_key(self) -> SecretStr | None:
        value = os.environ.get(self.api_key_env)
        return SecretStr(value) if value else None


class DatabaseSettings(BaseModel):
    dsn: str = "postgresql+asyncpg://pe_review:pe_review@postgres:5432/pe_review"
    pool_size: int = Field(default=5, ge=1, le=100)
    max_overflow: int = Field(default=5, ge=0, le=100)


class RepoSettings(BaseModel):
    cache_root: Path = Path("/var/lib/pe-review-agent/repos")
    work_root: Path = Path("/var/lib/pe-review-agent/work")
    max_diff_bytes: int = Field(default=1_500_000, ge=4096)
    command_timeout_seconds: float = Field(default=120.0, gt=0)


class ReviewSettings(BaseModel):
    policy_version: str = "firmware-v1"
    max_findings: int = Field(default=8, ge=0, le=50)
    min_confidence: float = Field(default=0.82, ge=0.0, le=1.0)
    max_tool_rounds: int = Field(default=8, ge=0, le=32)
    max_context_file_bytes: int = Field(default=256_000, ge=1024)
    generated_path_patterns: list[str] = Field(
        default_factory=lambda: [
            "*.bin",
            "*.hex",
            "*.map",
            "*.o",
            "*.a",
            "*.so",
            "*.elf",
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
        ]
    )


class RetrySettings(BaseModel):
    fetch_attempts: int = Field(default=4, ge=1, le=20)
    review_attempts: int = Field(default=4, ge=1, le=20)
    publish_attempts: int = Field(default=8, ge=1, le=50)
    base_seconds: float = Field(default=2.0, gt=0)
    max_seconds: float = Field(default=300.0, gt=0)
    jitter_ratio: float = Field(default=0.2, ge=0.0, le=1.0)


class ServiceSettings(BaseModel):
    worker_concurrency: int = Field(default=2, ge=1, le=32)
    claim_lease_seconds: int = Field(default=900, ge=30)
    poll_interval_seconds: float = Field(default=2.0, gt=0)
    reconcile_interval_seconds: int = Field(default=300, ge=30)
    health_host: str = "0.0.0.0"
    health_port: int = Field(default=8080, ge=1, le=65535)


class Settings(BaseModel):
    gerrit: GerritSettings
    llm: LlmSettings
    database: DatabaseSettings = Field(default_factory=DatabaseSettings)
    repos: RepoSettings = Field(default_factory=RepoSettings)
    review: ReviewSettings = Field(default_factory=ReviewSettings)
    retry: RetrySettings = Field(default_factory=RetrySettings)
    service: ServiceSettings = Field(default_factory=ServiceSettings)


def load_settings(path: str | Path | None = None) -> Settings:
    config_path = Path(path or os.environ.get("PE_REVIEW_CONFIG", "config/config.yaml"))
    with config_path.open("r", encoding="utf-8") as handle:
        raw = yaml.safe_load(handle) or {}
    raw = _apply_env_overrides(raw)
    return Settings.model_validate(raw)


def _apply_env_overrides(raw: dict[str, Any]) -> dict[str, Any]:
    """Apply PE_REVIEW__SECTION__KEY overrides without exposing secret values in YAML."""
    prefix = "PE_REVIEW__"
    merged = dict(raw)
    for key, value in os.environ.items():
        if not key.startswith(prefix):
            continue
        parts = [part.lower() for part in key[len(prefix) :].split("__") if part]
        if not parts:
            continue
        cursor: dict[str, Any] = merged
        for part in parts[:-1]:
            child = cursor.get(part)
            if not isinstance(child, dict):
                child = {}
                cursor[part] = child
            cursor = child
        cursor[parts[-1]] = yaml.safe_load(value)
    return merged
