from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field, SecretStr
from sqlalchemy.engine import URL, make_url


class StrictSettingsModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class GerritRestAuth(StrictSettingsModel):
    mode: Literal["none", "basic", "bearer"] = "none"
    username: str | None = None
    password_env: str | None = None
    token_env: str | None = None

    def secret(self) -> str | None:
        env_name = self.password_env if self.mode == "basic" else self.token_env
        return os.environ.get(env_name) if env_name else None


class GerritSettings(StrictSettingsModel):
    ssh_host: str
    ssh_port: int = Field(default=29418, ge=1, le=65535)
    ssh_user: str
    ssh_key_path: Path
    known_hosts_path: Path | None = None
    strict_host_key_checking: bool = True
    rest_url: str
    rest_auth: GerritRestAuth = Field(default_factory=GerritRestAuth)
    # Optional bootstrap allowlist. The Admin Web can start from an empty list and persist projects.
    projects: list[str] = Field(default_factory=list)
    event_reconnect_min_seconds: float = Field(default=1.0, gt=0)
    event_reconnect_max_seconds: float = Field(default=60.0, gt=0)
    request_timeout_seconds: float = Field(default=20.0, gt=0)
    ca_bundle_path: Path | None = None
    review_tag: str = "autogenerated:pe-ai-review"
    notify: Literal["NONE", "OWNER", "OWNER_REVIEWERS", "ALL"] = "OWNER"
    # Gerrit 3.8 change.commentSizeLimit defaults to 16 KiB. Keep individual change/inline
    # messages below the configured server ceiling so one verbose model finding cannot reject the
    # whole Set Review request.
    max_comment_bytes: int = Field(default=16 * 1024, ge=1024, le=3 * 1024 * 1024)


class LlmSettings(StrictSettingsModel):
    base_url: str
    model: str = "Qwen3.6-27B"
    api_key_env: str = "PE_REVIEW_LLM_API_KEY"
    request_timeout_seconds: float = Field(default=180.0, gt=0)
    connect_timeout_seconds: float = Field(default=10.0, gt=0)
    concurrency: int = Field(default=2, ge=1, le=64)
    temperature: float = Field(default=0.1, ge=0.0, le=2.0)
    max_output_tokens: int = Field(default=6000, ge=256)
    ca_bundle_path: Path | None = None

    @property
    def api_key(self) -> SecretStr | None:
        value = os.environ.get(self.api_key_env)
        return SecretStr(value) if value else None


class DatabaseSettings(StrictSettingsModel):
    dsn: str | None = None
    host: str = "postgres"
    port: int = Field(default=5432, ge=1, le=65535)
    username: str = "pe_review"
    database: str = "pe_review"
    password_env: str = "POSTGRES_PASSWORD"
    pool_size: int = Field(default=5, ge=1, le=100)
    max_overflow: int = Field(default=5, ge=0, le=100)

    def connection_url(self) -> URL:
        if self.dsn:
            return make_url(self.dsn)
        password = os.environ.get(self.password_env)
        if password is None:
            raise ValueError(
                f"database password environment variable {self.password_env!r} is not set"
            )
        return URL.create(
            "postgresql+asyncpg",
            username=self.username,
            password=password,
            host=self.host,
            port=self.port,
            database=self.database,
        )


class RepoSettings(StrictSettingsModel):
    cache_root: Path = Path("/var/lib/pe-review-agent/repos")
    work_root: Path = Path("/var/lib/pe-review-agent/work")
    # Absolute host-safety ceiling. Model context is handled independently by diff chunking.
    max_diff_bytes: int = Field(default=4_000_000, ge=4096)
    command_timeout_seconds: float = Field(default=120.0, gt=0)


class ReviewSettings(StrictSettingsModel):
    policy_version: str = "firmware-v1"
    output_language: Literal["ko-KR", "en-US"] = "ko-KR"
    max_findings: int = Field(default=8, ge=0, le=50)
    min_confidence: float = Field(default=0.82, ge=0.0, le=1.0)
    max_tool_rounds: int = Field(default=8, ge=0, le=32)
    max_context_file_bytes: int = Field(default=256_000, ge=1024)
    max_policy_bytes: int = Field(default=128_000, ge=1024, le=1_000_000)
    max_diff_chunk_chars: int = Field(default=70_000, ge=4_000, le=500_000)
    max_candidate_findings_total: int = Field(default=64, ge=1, le=256)
    tool_command_timeout_seconds: float = Field(default=20.0, gt=0, le=300)
    max_tool_output_bytes: int = Field(default=256_000, ge=4096, le=4_000_000)
    generated_path_patterns: list[str] = Field(
        default_factory=lambda: [
            "*.bin",
            "*.hex",
            "*.map",
            "*.o",
            "*.a",
            "*.so",
            "*.elf",
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
        ]
    )


class RetrySettings(StrictSettingsModel):
    fetch_attempts: int = Field(default=4, ge=1, le=20)
    review_attempts: int = Field(default=4, ge=1, le=20)
    publish_attempts: int = Field(default=8, ge=1, le=50)
    base_seconds: float = Field(default=2.0, gt=0)
    max_seconds: float = Field(default=300.0, gt=0)
    jitter_ratio: float = Field(default=0.2, ge=0.0, le=1.0)


class ServiceSettings(StrictSettingsModel):
    enabled: bool = True
    worker_concurrency: int = Field(default=2, ge=1, le=32)
    claim_lease_seconds: int = Field(default=900, ge=30)
    poll_interval_seconds: float = Field(default=2.0, gt=0)
    reconcile_interval_seconds: int = Field(default=300, ge=30)
    reconcile_full_sweep_interval_seconds: int = Field(default=3600, ge=60)
    health_host: str = "0.0.0.0"
    health_port: int = Field(default=8081, ge=1, le=65535)


class AdminSettings(StrictSettingsModel):
    host: str = "0.0.0.0"
    port: int = Field(default=8080, ge=1, le=65535)
    auth_mode: Literal["basic", "none"] = "basic"
    username: str = "admin"
    password_env: str = "PE_REVIEW_ADMIN_PASSWORD"
    log_root: Path = Path("/var/lib/pe-review-agent/logs")

    @property
    def password(self) -> SecretStr | None:
        value = os.environ.get(self.password_env)
        return SecretStr(value) if value else None


class Settings(StrictSettingsModel):
    gerrit: GerritSettings
    llm: LlmSettings
    database: DatabaseSettings = Field(default_factory=DatabaseSettings)
    repos: RepoSettings = Field(default_factory=RepoSettings)
    review: ReviewSettings = Field(default_factory=ReviewSettings)
    retry: RetrySettings = Field(default_factory=RetrySettings)
    service: ServiceSettings = Field(default_factory=ServiceSettings)
    admin: AdminSettings = Field(default_factory=AdminSettings)


def load_settings(path: str | Path | None = None) -> Settings:
    config_path = Path(path or os.environ.get("PE_REVIEW_CONFIG", "config/config.yaml"))
    with config_path.open("r", encoding="utf-8") as handle:
        raw = yaml.safe_load(handle) or {}
    raw = _apply_env_overrides(raw)
    return Settings.model_validate(raw)


def _apply_env_overrides(raw: dict[str, Any]) -> dict[str, Any]:
    """Apply PE_REVIEW__SECTION__KEY overrides without exposing secret values in YAML."""
    prefix = "PE_REVIEW__"
    merged = dict(raw)
    for key, value in os.environ.items():
        if not key.startswith(prefix):
            continue
        parts = [part.lower() for part in key[len(prefix) :].split("__") if part]
        if not parts:
            continue
        cursor: dict[str, Any] = merged
        for part in parts[:-1]:
            child = cursor.get(part)
            if not isinstance(child, dict):
                child = {}
                cursor[part] = child
            cursor = child
        cursor[parts[-1]] = yaml.safe_load(value)
    return merged
