from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

import httpx
import pytest

from pe_review_agent.config import GerritRestAuth, GerritSettings
from pe_review_agent.domain import DiffSide, Finding, FindingLocation, ReviewResult, Severity
from pe_review_agent.gerrit import GerritRestClient, SupersededRevisionError, build_review_input
from pe_review_agent.retry import PermanentError, TransientError

REVISION = "a" * 40
NEW_REVISION = "b" * 40


def _settings(
    *,
    auth: GerritRestAuth | None = None,
    projects: list[str] | None = None,
) -> GerritSettings:
    return GerritSettings(
        ssh_host="gerrit.internal",
        ssh_user="review-bot",
        ssh_key_path=Path("/run/secrets/gerrit_key"),
        rest_url="https://gerrit.internal/gerrit",
        rest_auth=auth or GerritRestAuth(mode="none"),
        projects=projects or ["team/fw"],
        review_tag="autogenerated:pe-ai-review",
        notify="OWNER_REVIEWERS",
    )


def _change_info(
    *,
    project: str = "team/fw",
    number: int = 123,
    revision: str = REVISION,
    patchset: int = 4,
    more: bool = False,
    updated: str = "2026-09-16 06:00:00.000000000",
    created: str | None = None,
    status: str = "NEW",
) -> dict[str, object]:
    payload: dict[str, object] = {
        "id": f"{project}~main~Ideadbeef",
        "project": project,
        "branch": "main",
        "change_id": "Ideadbeef",
        "subject": "Fix memory ordering",
        "status": status,
        "updated": updated,
        "_number": number,
        "current_revision": revision,
        "revisions": {
            revision: {
                "_number": patchset,
                "ref": f"refs/changes/{number % 100:02d}/{number}/{patchset}",
                "uploader": {"username": "alice"},
                "created": created or updated,
                "commit": {"message": "Fix memory ordering\n\nAvoid stale reads."},
            }
        },
    }
    if more:
        payload["_more_changes"] = True
    return payload


def _gerrit_json(payload: object, *, status_code: int = 200, **headers: str) -> httpx.Response:
    body = ")]}'\n" + json.dumps(payload)
    return httpx.Response(status_code, text=body, headers=headers)


@pytest.mark.asyncio
async def test_get_change_handles_xssi_prefix_and_context_path() -> None:
    seen: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return _gerrit_json(_change_info())

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        change = await client.get_change("team/fw", 123, include_commit=True)

    assert change.current_revision == REVISION
    assert change.patchset_number == 4
    assert change.ref == "refs/changes/23/123/4"
    assert change.commit_message == "Fix memory ordering\n\nAvoid stale reads."
    assert seen[0].url.raw_path.decode().split("?", 1)[0] == (
        "/gerrit/changes/team%2Ffw~123/detail"
    )
    assert seen[0].url.params.get_list("o") == ["CURRENT_REVISION", "CURRENT_COMMIT"]


@pytest.mark.asyncio
async def test_basic_auth_uses_authenticated_a_prefix(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("GERRIT_PASSWORD", "secret")
    auth = GerritRestAuth(mode="basic", username="review-bot", password_env="GERRIT_PASSWORD")
    seen: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return _gerrit_json(_change_info())

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(auth=auth), client=http_client)
        await client.get_change("team/fw", 123)

    assert seen[0].url.path.startswith("/gerrit/a/changes/")
    assert seen[0].url.params.get_list("o") == ["CURRENT_REVISION"]
    assert seen[0].headers["Authorization"].startswith("Basic ")


@pytest.mark.asyncio
async def test_bearer_auth_sets_authorization_header(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("GERRIT_TOKEN", "token-value")
    auth = GerritRestAuth(mode="bearer", token_env="GERRIT_TOKEN")
    seen: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return _gerrit_json(_change_info())

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(auth=auth), client=http_client)
        await client.get_change("team/fw", 123)

    assert seen[0].url.path.startswith("/gerrit/a/changes/")
    assert seen[0].headers["Authorization"] == "Bearer token-value"


@pytest.mark.asyncio
async def test_publish_review_builds_summary_inline_and_range_comments() -> None:
    requests: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        if request.method == "GET":
            return _gerrit_json(_change_info())
        return _gerrit_json({"labels": {}})

    review = ReviewResult(
        summary="Found two firmware correctness issues.",
        findings=[
            Finding(
                severity=Severity.P1,
                category="bounds",
                title="Unchecked descriptor index",
                message="The descriptor index can exceed the ring size.",
                impact="Out-of-bounds MMIO access.",
                evidence="idx is incremented without modulo reduction.",
                remediation="Mask or reduce idx before dereference.",
                location=FindingLocation(path="drivers/dma.c", start_line=88),
            ),
            Finding(
                severity=Severity.P2,
                category="locking",
                title="Lock scope misses update",
                message="The status update occurs after releasing the lock.",
                impact="A reader can observe stale state.",
                evidence="unlock precedes status assignment.",
                location=FindingLocation(
                    path="drivers/dma.c",
                    side=DiffSide.PARENT,
                    start_line=120,
                    start_character=4,
                    end_line=122,
                    end_character=9,
                ),
            ),
        ],
    )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        await client.publish_review(
            project="team/fw",
            change_number=123,
            revision_sha=REVISION,
            review=review,
        )

    assert [request.method for request in requests] == ["GET", "POST"]
    payload = json.loads(requests[1].content)
    assert payload["message"] == "Found two firmware correctness issues."
    assert payload["tag"] == "autogenerated:pe-ai-review"
    assert payload["notify"] == "OWNER_REVIEWERS"
    assert payload["omit_duplicate_comments"] is True
    assert "labels" not in payload
    line_comment, range_comment = payload["comments"]["drivers/dma.c"]
    assert line_comment["line"] == 88
    assert line_comment["side"] == "REVISION"
    assert "### `P1` Unchecked descriptor index" in line_comment["message"]
    assert "`Impact`\n\n> Out-of-bounds MMIO access." in line_comment["message"]
    assert (
        "`Evidence`\n\n> idx is incremented without modulo reduction." in line_comment["message"]
    )
    assert (
        "`Suggested fix`\n\n> Mask or reduce idx before dereference."
        in line_comment["message"]
    )
    assert range_comment["range"] == {
        "start_line": 120,
        "start_character": 4,
        "end_line": 122,
        "end_character": 9,
    }
    assert range_comment["side"] == "PARENT"
    assert "line" not in range_comment


def test_finding_message_preserves_multiline_section_readability() -> None:
    review = ReviewResult(
        summary="summary",
        findings=[
            Finding(
                severity=Severity.P1,
                category="mmio",
                title="Shared register is overwritten",
                message="The marker overwrites the address channel.",
                impact="First consequence.\nSecond consequence.",
                evidence="fw.c:10 — address source\ninit.c:20 — marker write",
                remediation="Use a separate register.",
                location=FindingLocation(path="fw.c", start_line=10),
            )
        ],
        review_metadata={"output_language": "ko-KR"},
    )

    message = build_review_input(review)["comments"]["fw.c"][0]["message"]

    assert message.startswith("### `P1` Shared register is overwritten\n\n")
    assert "`영향`\n\n> First consequence.\n> Second consequence." in message
    assert "`근거`\n\n> fw.c:10 — address source\n> init.c:20 — marker write" in message
    assert "`수정 방향`\n\n> Use a separate register." in message


@pytest.mark.asyncio
async def test_publish_review_rejects_superseded_revision_before_post() -> None:
    methods: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        methods.append(request.method)
        return _gerrit_json(_change_info(revision=NEW_REVISION, patchset=5))

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(SupersededRevisionError) as caught:
            await client.publish_review(
                project="team/fw",
                change_number=123,
                revision_sha=REVISION,
                review=ReviewResult(summary="stale", findings=[]),
            )

    assert caught.value.actual == NEW_REVISION
    assert methods == ["GET"]


@pytest.mark.asyncio
async def test_publish_review_input_preserves_legacy_plain_persisted_payload() -> None:
    requests: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        if request.method == "GET":
            return _gerrit_json(_change_info())
        return _gerrit_json({"labels": {}})

    persisted_payload = {
        "message": "Stored summary",
        "tag": "autogenerated:pe-ai-review",
        "notify": "OWNER_REVIEWERS",
        "omit_duplicate_comments": True,
        "comments": {
            "drivers/dma.c": [
                {
                    "line": 88,
                    "message": (
                        "[P1] Legacy plain title\n\n"
                        "Legacy description\n\n"
                        "Impact: legacy impact\n\n"
                        "Evidence: legacy evidence"
                    ),
                }
            ]
        },
    }

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        await client.publish_review_input(
            project="team/fw",
            change_number=123,
            revision_sha=REVISION,
            payload=persisted_payload,
        )

    assert [request.method for request in requests] == ["GET", "POST"]
    assert json.loads(requests[1].content) == persisted_payload


@pytest.mark.asyncio
async def test_publish_review_input_rejects_superseded_revision_before_post() -> None:
    methods: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        methods.append(request.method)
        return _gerrit_json(_change_info(revision=NEW_REVISION, patchset=5))

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(SupersededRevisionError):
            await client.publish_review_input(
                project="team/fw",
                change_number=123,
                revision_sha=REVISION,
                payload={"message": "Stored summary"},
            )

    assert methods == ["GET"]


@pytest.mark.asyncio
async def test_publish_review_input_can_comment_on_merged_same_revision() -> None:
    methods: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        methods.append(request.method)
        if request.method == "GET":
            return _gerrit_json(_change_info(status="MERGED"))
        return _gerrit_json({"labels": {}})

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        result = await client.publish_review_input(
            project="team/fw",
            change_number=123,
            revision_sha=REVISION,
            payload={"message": "Review completed before merge"},
            allow_merged=True,
        )

    assert result == {"labels": {}}
    assert methods == ["GET", "POST"]


@pytest.mark.asyncio
async def test_publish_review_input_merged_still_rejects_different_revision() -> None:
    methods: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        methods.append(request.method)
        return _gerrit_json(_change_info(status="MERGED", revision=NEW_REVISION, patchset=5))

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(SupersededRevisionError):
            await client.publish_review_input(
                project="team/fw",
                change_number=123,
                revision_sha=REVISION,
                payload={"message": "stale"},
                allow_merged=True,
            )

    assert methods == ["GET"]


@pytest.mark.asyncio
async def test_publish_review_input_runs_local_guard_after_gerrit_revision_check() -> None:
    methods: list[str] = []
    guard_calls = 0

    def handler(request: httpx.Request) -> httpx.Response:
        methods.append(request.method)
        return _gerrit_json(_change_info())

    async def guard() -> bool:
        nonlocal guard_calls
        guard_calls += 1
        return False

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(SupersededRevisionError) as caught:
            await client.publish_review_input(
                project="team/fw",
                change_number=123,
                revision_sha=REVISION,
                payload={"message": "Stored summary"},
                pre_post_guard=guard,
            )

    assert caught.value.actual == "newer-patchset-known-by-worker"
    assert guard_calls == 1
    assert methods == ["GET"]


@pytest.mark.asyncio
async def test_has_published_review_matches_patchset_tag_and_normalized_summary() -> None:
    paths: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        paths.append(request.url.path)
        return _gerrit_json(
            [
                {
                    "message": "Patch Set 4:\n\nFound two issues",
                    "tag": "autogenerated:another-reviewer",
                    "_revision_number": 4,
                },
                {
                    "message": "Patch Set 3:\n\nFound two issues",
                    "tag": "autogenerated:pe-ai-review",
                    "_revision_number": 3,
                },
                {
                    "message": "Patch Set 4:\n\n  Found   two\nissues  ",
                    "tag": "autogenerated:pe-ai-review",
                    "_revision_number": 4,
                },
            ]
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        published = await client.has_published_review(
            project="team/fw",
            change_number=123,
            patchset_number=4,
            summary="Found two issues",
        )

    assert published is True
    assert paths == ["/gerrit/changes/team/fw~123/messages"]


@pytest.mark.asyncio
async def test_has_published_review_ignores_gerrit_inline_comment_count_decoration() -> None:
    def handler(_: httpx.Request) -> httpx.Response:
        return _gerrit_json(
            [
                {
                    "message": "Patch Set 4:\n\n(2 comments)\n\nFound two issues",
                    "tag": "autogenerated:pe-ai-review~firmware-v1",
                    "_revision_number": 4,
                }
            ]
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        published = await client.has_published_review(
            project="team/fw",
            change_number=123,
            patchset_number=4,
            summary="Found two issues",
            tag="autogenerated:pe-ai-review~firmware-v1",
        )

    assert published is True


@pytest.mark.asyncio
async def test_has_published_review_requires_exact_explicit_policy_tag() -> None:
    def handler(_: httpx.Request) -> httpx.Response:
        return _gerrit_json(
            [
                {
                    "message": "Patch Set 4:\n\nFound two issues",
                    "tag": "autogenerated:pe-ai-review~firmware-v1",
                    "_revision_number": 4,
                }
            ]
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        old_policy = await client.has_published_review(
            project="team/fw",
            change_number=123,
            patchset_number=4,
            summary="Found two issues",
            tag="autogenerated:pe-ai-review~firmware-v1",
        )
        new_policy = await client.has_published_review(
            project="team/fw",
            change_number=123,
            patchset_number=4,
            summary="Found two issues",
            tag="autogenerated:pe-ai-review~firmware-v2",
        )

    assert old_policy is True
    assert new_policy is False


@pytest.mark.asyncio
async def test_has_published_review_rejects_message_mismatch() -> None:
    def handler(_: httpx.Request) -> httpx.Response:
        return _gerrit_json(
            [
                {
                    "message": "Patch Set 4:\n\nDifferent review summary",
                    "tag": "autogenerated:pe-ai-review",
                    "_revision_number": 4,
                }
            ]
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        published = await client.has_published_review(
            project="team/fw",
            change_number=123,
            patchset_number=4,
            summary="Found two issues",
        )

    assert published is False


@pytest.mark.asyncio
async def test_rest_errors_are_classified_for_retry() -> None:
    responses = iter(
        [
            httpx.Response(429, headers={"Retry-After": "7"}),
            httpx.Response(503),
            httpx.Response(403),
            httpx.Response(404),
        ]
    )

    def handler(_: httpx.Request) -> httpx.Response:
        return next(responses)

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)

        with pytest.raises(TransientError) as throttled:
            await client.get_change("team/fw", 123)
        assert throttled.value.retry_after_seconds == 7.0

        with pytest.raises(TransientError):
            await client.get_change("team/fw", 123)
        with pytest.raises(PermanentError):
            await client.get_change("team/fw", 123)
        with pytest.raises(PermanentError):
            await client.get_change("team/fw", 123)


@pytest.mark.asyncio
async def test_http_timeout_is_transient() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        raise httpx.ReadTimeout("slow Gerrit", request=request)

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(TransientError, match="timed out"):
            await client.get_change("team/fw", 123)


@pytest.mark.asyncio
async def test_rest_client_rejects_non_allowlisted_project_without_request() -> None:
    requests = 0

    def handler(_: httpx.Request) -> httpx.Response:
        nonlocal requests
        requests += 1
        return _gerrit_json(_change_info())

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(PermanentError, match="not allowlisted"):
            await client.get_change("team/other", 123)

    assert requests == 0


@pytest.mark.asyncio
async def test_reconciliation_query_paginates_recent_open_allowlisted_changes() -> None:
    queries: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        queries.append(request.url.params["q"])
        query = request.url.params["q"]
        assert "S" not in request.url.params
        if "before:" not in query:
            return _gerrit_json(
                [
                    _change_info(
                        number=123,
                        more=True,
                        updated="2026-09-16 06:00:00.100000000",
                    ),
                    _change_info(
                        number=124,
                        more=True,
                        updated="2026-09-16 05:00:00.900000001",
                    ),
                ]
            )
        if "-change:125" not in query:
            assert "-change:124" in query
            return _gerrit_json(
                [
                    _change_info(
                        number=125,
                        revision=NEW_REVISION,
                        patchset=2,
                        more=True,
                        updated="2026-09-16 05:00:00.900000999",
                    )
                ]
            )
        assert "-change:124" in query and "-change:125" in query
        return _gerrit_json(
            [
                _change_info(
                    number=126,
                    revision=NEW_REVISION,
                    patchset=2,
                    updated="2026-09-16 04:59:59.999000000",
                )
            ]
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        events = await client.reconciliation_events(
            since=datetime(2026, 9, 16, 4, 30, tzinfo=UTC),
            page_size=2,
        )

    assert all('project:"team/fw"' in query for query in queries)
    assert all('after:"2026-09-16 04:30:00 +0000"' in query for query in queries)
    assert 'before:"2026-09-16 05:00:00.901 +0000"' in queries[1]
    assert 'before:"2026-09-16 05:00:00.901 +0000"' in queries[2]
    identities = [(event.change_number, event.patchset_number) for event in events]
    assert identities == [(123, 4), (124, 4), (125, 2), (126, 2)]
    assert events[0].uploader == "alice"
    assert events[0].raw["type"] == "reconciliation"


@pytest.mark.asyncio
async def test_reconciliation_bootstrap_queries_all_open_allowlisted_changes() -> None:
    queries: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        queries.append(request.url.params["q"])
        return _gerrit_json([_change_info()])

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        events = await client.reconciliation_events(since=None)

    assert len(events) == 1
    assert queries == ['status:open project:"team/fw"']


@pytest.mark.asyncio
async def test_reconciliation_project_cutoff_avoids_old_open_patchsets() -> None:
    queries: list[str] = []
    cutoff = datetime(2026, 9, 16, 5, 30, tzinfo=UTC)

    def handler(request: httpx.Request) -> httpx.Response:
        queries.append(request.url.params["q"])
        return _gerrit_json(
            [
                _change_info(
                    number=201,
                    updated="2026-09-16 06:10:00.000000000",
                    created="2026-09-16 05:00:00.000000000",
                ),
                _change_info(
                    number=202,
                    revision=NEW_REVISION,
                    patchset=2,
                    updated="2026-09-16 06:05:00.000000000",
                    created="2026-09-16 05:45:00.000000000",
                ),
            ]
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        events = await client.reconciliation_events(
            since=None,
            project_since={"team/fw": cutoff},
        )

    assert queries == ['status:open project:"team/fw" after:"2026-09-16 05:30:00 +0000"']
    assert [(event.change_number, event.patchset_number) for event in events] == [(202, 2)]


def test_review_input_caps_summary_and_inline_comments_by_utf8_bytes() -> None:
    review = ReviewResult(
        summary="요약" * 2000,
        findings=[
            Finding(
                severity=Severity.P1,
                category="timeout",
                title="Timeout failure " * 500,
                message="상세 설명" * 2000,
                impact="stale data " * 1000,
                evidence="poll() " * 1000,
                remediation="propagate " * 1000,
                location=FindingLocation(path="fw/train.c", start_line=7),
                confidence=0.99,
            )
        ],
    )

    payload = build_review_input(review, max_comment_bytes=1024)

    assert len(payload["message"].encode("utf-8")) <= 1024
    inline = payload["comments"]["fw/train.c"][0]["message"]
    assert len(inline.encode("utf-8")) <= 1024
    assert inline.endswith("[truncated by review bot to Gerrit comment size limit]")


@pytest.mark.asyncio
async def test_get_revision_commit_uses_requested_revision() -> None:
    seen_paths: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen_paths.append(request.url.path)
        return _gerrit_json({"commit": REVISION, "subject": "Fix memory ordering"})

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        commit = await client.get_revision_commit("team/fw", 123, REVISION)

    assert commit["commit"] == REVISION
    assert seen_paths == [f"/gerrit/changes/team/fw~123/revisions/{REVISION}/commit"]
