from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

import httpx
import pytest

from pe_review_agent.config import GerritRestAuth, GerritSettings
from pe_review_agent.domain import Finding, FindingLocation, ReviewResult, Severity
from pe_review_agent.gerrit import GerritRestClient, SupersededRevisionError
from pe_review_agent.retry import PermanentError, TransientError

REVISION = "a" * 40
NEW_REVISION = "b" * 40


def _settings(
    *,
    auth: GerritRestAuth | None = None,
    projects: list[str] | None = None,
) -> GerritSettings:
    return GerritSettings(
        ssh_host="gerrit.internal",
        ssh_user="review-bot",
        ssh_key_path=Path("/run/secrets/gerrit_key"),
        rest_url="https://gerrit.internal/gerrit",
        rest_auth=auth or GerritRestAuth(mode="none"),
        projects=projects or ["team/fw"],
        review_tag="autogenerated:pe-ai-review",
        notify="OWNER_REVIEWERS",
    )


def _change_info(
    *,
    project: str = "team/fw",
    number: int = 123,
    revision: str = REVISION,
    patchset: int = 4,
    more: bool = False,
) -> dict[str, object]:
    payload: dict[str, object] = {
        "id": f"{project}~main~Ideadbeef",
        "project": project,
        "branch": "main",
        "change_id": "Ideadbeef",
        "subject": "Fix memory ordering",
        "status": "NEW",
        "updated": "2026-09-16 06:00:00.000000000",
        "_number": number,
        "current_revision": revision,
        "revisions": {
            revision: {
                "_number": patchset,
                "ref": f"refs/changes/{number % 100:02d}/{number}/{patchset}",
                "uploader": {"username": "alice"},
            }
        },
    }
    if more:
        payload["_more_changes"] = True
    return payload


def _gerrit_json(payload: object, *, status_code: int = 200, **headers: str) -> httpx.Response:
    body = ")]}'\n" + json.dumps(payload)
    return httpx.Response(status_code, text=body, headers=headers)


@pytest.mark.asyncio
async def test_get_change_handles_xssi_prefix_and_context_path() -> None:
    seen: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return _gerrit_json(_change_info())

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        change = await client.get_change("team/fw", 123)

    assert change.current_revision == REVISION
    assert change.patchset_number == 4
    assert change.ref == "refs/changes/23/123/4"
    assert seen[0].url.raw_path.decode().split("?", 1)[0] == (
        "/gerrit/changes/team%2Ffw~123/detail"
    )
    assert seen[0].url.params.get_list("o") == ["CURRENT_REVISION"]


@pytest.mark.asyncio
async def test_basic_auth_uses_authenticated_a_prefix(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("GERRIT_PASSWORD", "secret")
    auth = GerritRestAuth(mode="basic", username="review-bot", password_env="GERRIT_PASSWORD")
    seen: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return _gerrit_json(_change_info())

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(auth=auth), client=http_client)
        await client.get_change("team/fw", 123)

    assert seen[0].url.path.startswith("/gerrit/a/changes/")
    assert seen[0].headers["Authorization"].startswith("Basic ")


@pytest.mark.asyncio
async def test_bearer_auth_sets_authorization_header(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("GERRIT_TOKEN", "token-value")
    auth = GerritRestAuth(mode="bearer", token_env="GERRIT_TOKEN")
    seen: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return _gerrit_json(_change_info())

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(auth=auth), client=http_client)
        await client.get_change("team/fw", 123)

    assert seen[0].url.path.startswith("/gerrit/a/changes/")
    assert seen[0].headers["Authorization"] == "Bearer token-value"


@pytest.mark.asyncio
async def test_publish_review_builds_summary_inline_and_range_comments() -> None:
    requests: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        if request.method == "GET":
            return _gerrit_json(_change_info())
        return _gerrit_json({"labels": {}})

    review = ReviewResult(
        summary="Found two firmware correctness issues.",
        findings=[
            Finding(
                severity=Severity.P1,
                category="bounds",
                title="Unchecked descriptor index",
                message="The descriptor index can exceed the ring size.",
                impact="Out-of-bounds MMIO access.",
                evidence="idx is incremented without modulo reduction.",
                remediation="Mask or reduce idx before dereference.",
                location=FindingLocation(path="drivers/dma.c", start_line=88),
            ),
            Finding(
                severity=Severity.P2,
                category="locking",
                title="Lock scope misses update",
                message="The status update occurs after releasing the lock.",
                impact="A reader can observe stale state.",
                evidence="unlock precedes status assignment.",
                location=FindingLocation(
                    path="drivers/dma.c",
                    start_line=120,
                    start_character=4,
                    end_line=122,
                    end_character=9,
                ),
            ),
        ],
    )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        await client.publish_review(
            project="team/fw",
            change_number=123,
            revision_sha=REVISION,
            review=review,
        )

    assert [request.method for request in requests] == ["GET", "POST"]
    payload = json.loads(requests[1].content)
    assert payload["message"] == "Found two firmware correctness issues."
    assert payload["tag"] == "autogenerated:pe-ai-review"
    assert payload["notify"] == "OWNER_REVIEWERS"
    assert payload["omit_duplicate_comments"] is True
    assert "labels" not in payload
    line_comment, range_comment = payload["comments"]["drivers/dma.c"]
    assert line_comment["line"] == 88
    assert "[P1] Unchecked descriptor index" in line_comment["message"]
    assert range_comment["range"] == {
        "start_line": 120,
        "start_character": 4,
        "end_line": 122,
        "end_character": 9,
    }
    assert "line" not in range_comment


@pytest.mark.asyncio
async def test_publish_review_rejects_superseded_revision_before_post() -> None:
    methods: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        methods.append(request.method)
        return _gerrit_json(_change_info(revision=NEW_REVISION, patchset=5))

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(SupersededRevisionError) as caught:
            await client.publish_review(
                project="team/fw",
                change_number=123,
                revision_sha=REVISION,
                review=ReviewResult(summary="stale", findings=[]),
            )

    assert caught.value.actual == NEW_REVISION
    assert methods == ["GET"]


@pytest.mark.asyncio
async def test_publish_review_input_posts_persisted_payload_unchanged_after_revision_guard() -> (
    None
):
    requests: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        if request.method == "GET":
            return _gerrit_json(_change_info())
        return _gerrit_json({"labels": {}})

    persisted_payload = {
        "message": "Stored summary",
        "tag": "autogenerated:pe-ai-review",
        "notify": "OWNER_REVIEWERS",
        "omit_duplicate_comments": True,
        "comments": {
            "drivers/dma.c": [
                {
                    "line": 88,
                    "message": "Stored inline comment",
                }
            ]
        },
    }

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        await client.publish_review_input(
            project="team/fw",
            change_number=123,
            revision_sha=REVISION,
            payload=persisted_payload,
        )

    assert [request.method for request in requests] == ["GET", "POST"]
    assert json.loads(requests[1].content) == persisted_payload


@pytest.mark.asyncio
async def test_publish_review_input_rejects_superseded_revision_before_post() -> None:
    methods: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        methods.append(request.method)
        return _gerrit_json(_change_info(revision=NEW_REVISION, patchset=5))

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(SupersededRevisionError):
            await client.publish_review_input(
                project="team/fw",
                change_number=123,
                revision_sha=REVISION,
                payload={"message": "Stored summary"},
            )

    assert methods == ["GET"]


@pytest.mark.asyncio
async def test_has_published_review_matches_patchset_tag_and_normalized_summary() -> None:
    paths: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        paths.append(request.url.path)
        return _gerrit_json(
            [
                {
                    "message": "Patch Set 4:\n\nFound two issues",
                    "tag": "autogenerated:another-reviewer",
                    "_revision_number": 4,
                },
                {
                    "message": "Patch Set 3:\n\nFound two issues",
                    "tag": "autogenerated:pe-ai-review",
                    "_revision_number": 3,
                },
                {
                    "message": "Patch Set 4:\n\n  Found   two\nissues  ",
                    "tag": "autogenerated:pe-ai-review",
                    "_revision_number": 4,
                },
            ]
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        published = await client.has_published_review(
            project="team/fw",
            change_number=123,
            patchset_number=4,
            summary="Found two issues",
        )

    assert published is True
    assert paths == ["/gerrit/changes/team/fw~123/messages"]


@pytest.mark.asyncio
async def test_has_published_review_rejects_message_mismatch() -> None:
    def handler(_: httpx.Request) -> httpx.Response:
        return _gerrit_json(
            [
                {
                    "message": "Patch Set 4:\n\nDifferent review summary",
                    "tag": "autogenerated:pe-ai-review",
                    "_revision_number": 4,
                }
            ]
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        published = await client.has_published_review(
            project="team/fw",
            change_number=123,
            patchset_number=4,
            summary="Found two issues",
        )

    assert published is False


@pytest.mark.asyncio
async def test_rest_errors_are_classified_for_retry() -> None:
    responses = iter(
        [
            httpx.Response(429, headers={"Retry-After": "7"}),
            httpx.Response(503),
            httpx.Response(403),
            httpx.Response(404),
        ]
    )

    def handler(_: httpx.Request) -> httpx.Response:
        return next(responses)

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)

        with pytest.raises(TransientError) as throttled:
            await client.get_change("team/fw", 123)
        assert throttled.value.retry_after_seconds == 7.0

        with pytest.raises(TransientError):
            await client.get_change("team/fw", 123)
        with pytest.raises(PermanentError):
            await client.get_change("team/fw", 123)
        with pytest.raises(PermanentError):
            await client.get_change("team/fw", 123)


@pytest.mark.asyncio
async def test_http_timeout_is_transient() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        raise httpx.ReadTimeout("slow Gerrit", request=request)

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(TransientError, match="timed out"):
            await client.get_change("team/fw", 123)


@pytest.mark.asyncio
async def test_rest_client_rejects_non_allowlisted_project_without_request() -> None:
    requests = 0

    def handler(_: httpx.Request) -> httpx.Response:
        nonlocal requests
        requests += 1
        return _gerrit_json(_change_info())

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        with pytest.raises(PermanentError, match="not allowlisted"):
            await client.get_change("team/other", 123)

    assert requests == 0


@pytest.mark.asyncio
async def test_reconciliation_query_paginates_recent_open_allowlisted_changes() -> None:
    starts: list[str] = []
    queries: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        starts.append(request.url.params["S"])
        queries.append(request.url.params["q"])
        if request.url.params["S"] == "0":
            return _gerrit_json([_change_info(number=123, more=True)])
        return _gerrit_json([_change_info(number=124, revision=NEW_REVISION, patchset=2)])

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        events = await client.reconciliation_events(
            since=datetime(2026, 9, 16, 5, 30, tzinfo=UTC),
            page_size=1,
        )

    assert starts == ["0", "1"]
    assert all('project:"team/fw"' in query for query in queries)
    assert all('after:"2026-09-16 05:30:00 +0000"' in query for query in queries)
    identities = [(event.change_number, event.patchset_number) for event in events]
    assert identities == [(123, 4), (124, 2)]
    assert events[0].uploader == "alice"
    assert events[0].raw["type"] == "reconciliation"


@pytest.mark.asyncio
async def test_get_revision_commit_uses_requested_revision() -> None:
    seen_paths: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen_paths.append(request.url.path)
        return _gerrit_json({"commit": REVISION, "subject": "Fix memory ordering"})

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as http_client:
        client = GerritRestClient(_settings(), client=http_client)
        commit = await client.get_revision_commit("team/fw", 123, REVISION)

    assert commit["commit"] == REVISION
    assert seen_paths == [f"/gerrit/changes/team/fw~123/revisions/{REVISION}/commit"]
